# 1. List Sum: Write a program that takes a list of numbers as input and calculates the sum of all the numbers in the list.

In [ ]:
numbers = list(map(float, input("Enter numbers seperated by spaces: ").split()))
total = sum(numbers)
print(f"Sum = {total}")

Enter numbers seperated by commas: 76 54 34 23 88
Sum = 275.0

# 2. List Reversal: Write a program that takes a list of numbers as input and reverses the order of elements in the list.

In [ ]:
numbers = list(map(int, input("Enter numbers seperated by spaces: ").split()))
reverse = numbers[::-1]
print(f"Original : {numbers}")
print(f"Reversed : {reverse}")

Enter numbers seperated by commas: 7 6 5 4 3 2 1
Original : [7, 6, 5, 4, 3, 2, 1]
Reversed : [1, 2, 3, 4, 5, 6, 7]

# 3. List Sorting: Write a program that takes a list of numbers as input and sorts the list in ascending order.

In [ ]:
# Method 1

numbers = list(map(int, input("Enter numbers seperated by spacess: ").split()))
numbers.sort
print(numbers)

# Method 2

numbers = list(map(int, input("Enter numbers seperated by spaces: ").split()))
ascending_order = sorted(numbers)
print(f"Original : {numbers}")
print(f"Ascending : {ascending_order}")

# 4. List Filtering: Write a program that takes a list of numbers as input and filters out the even numbers, storing them in a new list.

In [ ]:
numbers = list(map(int, input("Enter numbers seperated by spaces: ").split()))
even_numbers = [num for num in numbers if num % 2 == 0]
print(f"Original : {numbers}")
print(f"Even Numbers : {even_numbers}")

# 5. List Element Search: Write a program that takes a list of numbers and a target number as input and checks if the target number is present in the list.

In [ ]:
numbers = list(map(int, input("Enter numbers seperated by spaces: ").split()))
target = int(input("Enter target number to search"))

if target in numbers:
  print(f"{target} i present in the list at index {numbers.index(target)}")
else:
  print(f"{target} is Not Present in the list")

# 6. Dictionary Key Access: Write a program that iterates over the keys of a dictionary and prints each key.

In [ ]:
person = {"name": "Venkatesh", "age": 22, "city": "vizag"}
for keys in person:
  print(keys)

# 7. Dictionary Value Access: Write a program that iterates over the values of a dictionary and prints each value.

In [ ]:
my_dict = {
    "A": 10,
    "B": 20,
    "C": 30
}

for value in my_dict.values():
  print(value)

10
20
30

# 8. Dictionary Item Access: Write a program that iterates over the items (key-value pairs) of a dictionary and prints each item.

In [ ]:
my_dict = {
    "A": 10,
    "B": 20,
    "C": 30
}

for pairs in my_dict.items():
  print(pairs)

('A', 10)
('B', 20)
('C', 30)

# 9. Tuple Element Access: Write a program that takes a tuple as input and prints each element of the tuple.

In [ ]:
tpl = (10, 20, 30, 40)
for item in tpl:
  print(item)

10
20
30
40

# 10. Tuple Packing and Unpacking: Write a program that packs and unpacks elements from a tuple.

In [ ]:
packed = (10, 20, 30)
print(packed)

a, b, c = packed

print(a)
print(b)
print(c)

(10, 20, 30)
10
20
30

# 11. Nested Data Structure Traversal: Write a program that iterates over a nested data structure (such as a list of lists) and prints each element.

# 12. **Tuple Sum**: Write a program that takes a tuple of integers as input and calculates the sum of all the elements in the tuple using a while loop. Return the sum.

In [ ]:
my_tuple = (10, 20, 30, 40)

i = 0
total = 0

while i < len(my_tuple):
  total += my_tuple[i]
  i += 1
print(total)

100

In [2]:
import pandas as pd
import numpy as np

In [4]:
data = ["Apple", "Banana", "Orange", "Mango"]

In [6]:
s1 = pd.Series(data)

In [7]:
s1

0     Apple
1    Banana
2    Orange
3     Mango
dtype: object

In [11]:
s1 = pd.Series(("Apple", "Banana", "Orange", "Mango"))
s1

0     Apple
1    Banana
2    Orange
3     Mango
dtype: object

In [ ]:
np.random.randint()

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
filepath = '/content/drive/MyDrive/student_records.csv'
df = pd.read_csv(filepath)

In [15]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90          85.0       Yes
1    John            C        N             85          51.0       Yes
2   David            F        N             10          17.0        No
3  Holmes            B        Y             75          71.0        No
4  Marvin            E        N             20          30.0        No
5   Simon            A        Y             92          79.0       Yes
6  Robert            B        Y             60          59.0        No
7   Trent            C        Y             75          33.0        No
8    Judy          NaN        Y             25           NaN        No
9   Chris            D        U             25          15.0        NO